import { IntentType } from '../enums/intent-type.enum';

export const INTENT_PATTERNS: Record<IntentType, string[]> = {

  [IntentType.ExplainTopic]: [

    'what is',
    'who is',
    'define',
    'meaning of',
    'explain',
    'explain again',
    'teach me',
    'teach again',
    'can you explain',
    'can you teach',
    'help me understand',
    'make me understand',
    'walk me through',
    'show me how',
    'show me',
    'describe',
    'clarify',
    'illustrate',
    'give explanation',
    'how does',
    'how do',
    'why does',
    'why do',
    'tell me about',
    'learn about',
    'understand',
    'concept of',
    'example of',
    'give example',
    'real life example',

  ],

  [IntentType.AskDoubt]: [

    'why',
    'how',
    'what',
    'when',
    'where',
    'which',
    'can you tell',
    'i do not understand',
    "i don't understand",
    'i am confused',
    "i'm confused",
    'why is',
    'how can',
    'how come',
    'is this correct',
    'am i right',
    'is my answer correct',
    'where did i go wrong',
    'what went wrong',
    'why is my answer wrong',
    'can you solve',
    'help me solve',
    'solve this',
    'check my answer',
    'find my mistake',

  ],

  [IntentType.NeedPractice]: [

    'practice',
    'practice questions',
    'give me questions',
    'give questions',
    'give me problems',
    'solve problems',
    'worksheet',
    'quiz me',
    'test me',
    'mock test',
    'challenge me',
    'daily practice',
    'more questions',
    'more practice',
    'easy questions',
    'medium questions',
    'hard questions',
    'timed practice',
    'speed test',
    'revision questions',

  ],

  [IntentType.StudyPlan]: [

    'study plan',
    'study next',
    'learn next',
    'what next',
    'continue learning',
    'next topic',
    'learning plan',
    'roadmap',
    'schedule',
    'routine',
    'learning path',
    'study routine',
    'prepare for exam',
    'exam preparation',
    'revision plan',
    'weekly plan',
    'monthly plan',
    'daily plan',
    'what should i study',
    'what do i study today',
    'how should i study',
    'plan my studies',
    'organize my study',

  ],

  [IntentType.Recommendation]: [

    'recommend',
    'recommend me',
    'suggest',
    'best way',
    'which is best',
    'what should i',
    'what next',
    'what should i learn next',
    'which topic next',
    'which sutra next',
    'next topic',
    'next chapter',
    'where should i start',
    'where do i begin',
    'guide me',
    'give recommendation',
    'suggest topic',
    'what is the next step',
    'continue learning',

  ],

  [IntentType.Greeting]: [

    'hello',
    'hi',
    'hey',
    'good morning',
    'good afternoon',
    'good evening',
    'good night',
    'nice to meet you',
    'how are you',
    'thanks',
    'thank you',
    'bye',
    'see you',

  ],

  [IntentType.Motivation]: [

    'motivate me',
    'encourage me',
    'boost my confidence',
    'help me improve',
    'i feel low',
    'i am losing confidence',
    "i'm losing confidence",
    'i feel discouraged',
    'i am frustrated',
    "i'm frustrated",
    'i feel stressed',
    'i am nervous',
    'i am scared',
    'i cannot do this',
    "i can't do this",
    'i keep making mistakes',
    'i want to improve',
    'help me become faster',
    'improve my speed',
    'improve my accuracy',
    'keep me motivated',

  ],

  [IntentType.Unknown]: [],

};
