export enum TutorIntent {
  ASK_CONCEPT = 'ASK_CONCEPT',
  ASK_HINT = 'ASK_HINT',
  ASK_SOLUTION = 'ASK_SOLUTION',
  CHECK_ANSWER = 'CHECK_ANSWER',
  EXPLAIN_MISTAKE = 'EXPLAIN_MISTAKE',
  ASK_EXAMPLE = 'ASK_EXAMPLE',
  ASK_SUTRA = 'ASK_SUTRA',
  ASK_NEXT_STEP = 'ASK_NEXT_STEP',
  PRACTICE_REQUEST = 'PRACTICE_REQUEST',
  GENERAL_LEARNING_QUERY = 'GENERAL_LEARNING_QUERY',
  UNKNOWN = 'UNKNOWN',
}
